import { Work_Sans } from 'next/font/google';

import Navbar from './components/Navbar';
import Provider from './components/Provider';
import './globals.css';

const work_sans = Work_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${work_sans.className} bg-lightPrimary dark:bg-darkPrimary text-lightPrimary dark:text-darkPrimary`}
      >
        <Navbar />
        <main className="max-w-[98%] md:max-w-6xl mx-auto md:px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
